---
kind: ConfigMap
apiVersion: v1
metadata:
  name: env-config
data:
  POSTGRES_HOST: host
  POSTGRES_DB: postgres
  AWS_BUCKET: myawsbucket-new-new
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100
