---
kind: ConfigMap
apiVersion: v1
metadata:
  name: env-config
data:
  POSTGRES_HOST: database-1.chjeuyquiior.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: myawsbucket-new
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: testing
  URL: http://localhost:8100
